apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - 'bookinfo'
    labelSelectors:
      'app': 'reviews'
  stressors:
    cpu:
      workers: 2
      load: 100