apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - 'bookinfo'
    labelSelectors:
      'app': 'productpage'
  delay:
    latency: '100ms'
    correlation: '100'
    jitter: '0ms'